export const colors = {
  brand: {
    primary: "#3D6CB9",
    secondary: "##bae8e8",
    linear: ["#bae8e8", "#83B4FF"],
  },
  ui: {
    disabled: "#AAAAAA",
    white: "#FFFFFF",
    border: "#C2C2C2",
    lightBorder: "#E3E7EB",
    errorBox: "#DC3545",
    notification: "#FF2525",
    rejectedBox: "#ECABB1",
    redDot: "#E41313",
    greenDot: "#1CCD1B",
    blue: "#146CC8",
  },
  bg: {
    primary: "#F4F4F4",
    secondary: "#FFFFFF",
    formContainerBg: "#FFFFFF",
    sessionCardBg: "#E3E7EB",
    grey: "#F0F3F9",
  },
  text: {
    primary: "#000000",
    secondary: "#868D96",
    placeholder: "#868D96",
    table: "#6B6B6B",
    white: "#FFFFFF",
    disabled: "#AAAAAA",
    error: "#d32f2f",
    rejected: "#DC3545",
    yellow: "#F2BA00",
    link: "#3874cb",
  },
  button: {
    idle: "#E3E7EB",
    disabled: "#7B828B",
  },
};
